#ifndef DEEPSPACE_H
#define DEEPSPACE_H

/* NOTE: This file is generated by cbindgen from deepspace/src/ffi.rs — do not edit manually. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


/**
 * 返回码：0 成功；负值对应错误
 */
#define DS_OK 0

#define DS_ERR_NULL -1

#define DS_ERR_NOT_FOUND -2

#define DS_ERR_INVALID_ARG -3

#define DS_ERR_OOM -4

#define DS_ERR_STATE -5

#define DSEV_INFO 0

#define DSEV_DETECT 1

#define DSEV_LAUNCH 2

#define DSEV_HIT 3

#define DSEV_PHASE 4

#define DSEV_OUTCOME 5

#define EnduranceStation_RADIUS 40.0

#define EnduranceStation_NORMAL_RPM 5.6

#define EnduranceStation_EMERGENCY_RPM 68.0

/**
 * 统一实体类型标签（与 [`EntityKind`] 一一对应）
 */
typedef enum DSEntityKind {
  DsEntityKindRocket = 0,
  DsEntityKindSpacecraft = 1,
  DsEntityKindMissile = 2,
  DsEntityKindIcbm = 3,
  DsEntityKindAircraft = 4,
  DsEntityKindBody = 5,
} DSEntityKind;

/**
 * FFI 句柄：指向内部 [`World`] 的不透明指针。
 *
 * 无 `#[repr(C)]` 且字段私有 → cbindgen 生成 `typedef struct DSWorld DSWorld;`，
 * C 侧只见不透明句柄，不感知内部 [`World`] 的内存布局。
 */
typedef struct DSWorld DSWorld;

typedef struct FrameId FrameId;

/**
 * 三维向量（f64）
 */
typedef struct DSVec3 {
  double x;
  double y;
  double z;
} DSVec3;

/**
 * 6DOF 航天器配置
 */
typedef struct DSSpacecraftConfig {
  char name[64];
  struct DSVec3 position;
  struct DSVec3 velocity;
  double mass;
  double inertia_xx;
  double inertia_yy;
  double inertia_zz;
} DSSpacecraftConfig;

/**
 * 弹道目标配置（新建弹道目标用）
 */
typedef struct DSBallisticConfig {
  char name[64];
  struct DSVec3 position;
  struct DSVec3 velocity;
  double mass;
  double ref_area_m2;
  double cd;
  double thrust_n;
  double thrust_duration_s;
} DSBallisticConfig;

/**
 * 统一实体状态快照（外部引擎每帧读这里渲染）
 */
typedef struct DSEntityState {
  /**
   * 实体 id（稳定句柄）
   */
  uint64_t id;
  /**
   * 实体类型
   */
  enum DSEntityKind kind;
  /**
   * 世界坐标位置 (m)
   */
  struct DSVec3 position;
  /**
   * 世界坐标速度 (m/s)
   */
  struct DSVec3 velocity;
  /**
   * 加速度 (m/s²)
   */
  struct DSVec3 acceleration;
  /**
   * 离地表海拔 (m)
   */
  double altitude_m;
  /**
   * 是否存活
   */
  bool alive;
  /**
   * 显示名（固定缓冲，截断安全）
   */
  char name[64];
  /**
   * 状态文本（如拦截阶段 / G 值）
   */
  char status[64];
} DSEntityState;

/**
 * 世界事件（闭环反馈日志）
 */
typedef struct DSEvent {
  /**
   * 世界时间 (s)
   */
  double time;
  /**
   * 事件类型
   */
  uint32_t kind;
  /**
   * 事件文本
   */
  char text[256];
} DSEvent;



/**
 * 创建一个标准统一世界（地球固定在原点 + 默认大气 + APG-77 雷达）
 *
 * 等价于 [`World::default`]。返回句柄，用 [`ds_world_destroy`] 释放。
 *
 * # Safety
 * 返回的指针必须用 [`ds_world_destroy`] 释放，不得跨线程移动。
 */
struct DSWorld *ds_world_create(void);

/**
 * 释放世界
 *
 * # Safety
 * `world` 必须来自 [`ds_world_create`] 且未释放过。
 */
void ds_world_destroy(struct DSWorld *world);

/**
 * 推进一个世界步（N 体 + 航天器 + 弹道 + 拦截 + 探测 + 命中）
 *
 * # Safety
 * `world` 必须有效。
 */
int32_t ds_world_step(struct DSWorld *world);

/**
 * 当前世界时间 (s)
 *
 * # Safety
 * `world` 必须有效。
 */
double ds_world_time(struct DSWorld *world);

/**
 * 最后一条错误消息（线程局部，UTF-8）
 *
 * # Safety
 * `buf` 必须指向至少 `buf_len` 字节的可写内存（`buf` 为空时仅返回长度）。
 */
size_t ds_last_error_message(char *buf, size_t buf_len);

/**
 * 注册一个 6DOF 航天器，返回实体 id（-1 失败）
 *
 * # Safety
 * `world` 有效；`cfg` 非空。
 */
int64_t ds_world_add_spacecraft(struct DSWorld *world, const struct DSSpacecraftConfig *cfg);

/**
 * 添加一颗圆轨道卫星（绕世界原点，给定海拔与倾角）
 *
 * # Safety
 * `world` 有效。
 */
int64_t ds_world_add_satellite(struct DSWorld *world,
                               const char *name,
                               double altitude_m,
                               double inclination_rad);

/**
 * 添加弹道目标（ICBM / 靶弹），返回实体 id
 *
 * # Safety
 * `world`、`cfg` 有效。
 */
int64_t ds_world_add_ballistic(struct DSWorld *world, const struct DSBallisticConfig *cfg);

/**
 * 发射一枚拦截导弹拦截指定目标，返回拦截弹实体 id（-1 失败）
 *
 * # Safety
 * `world` 有效。
 */
int64_t ds_world_fire_interceptor(struct DSWorld *world,
                                  uint64_t target_id,
                                  struct DSVec3 pos,
                                  struct DSVec3 vel);

/**
 * 雷达探测到第一个存活弹道目标 id（无则 -1）
 *
 * # Safety
 * `world` 有效。
 */
int64_t ds_world_detected_target(struct DSWorld *world);

/**
 * 实体总数（HUD 遍历用）
 *
 * # Safety
 * `world` 有效。
 */
size_t ds_world_entity_count(struct DSWorld *world);

/**
 * 按索引取实体状态（实体表是有序的，索引 ∈ [0, count)）。
 *
 * 把状态拷贝到 `out`（非空）。不存在或越界返回负错误码。
 *
 * # Safety
 * `world`、`out` 有效；`out` 需指向足够大的 `[DSEntityState]` 缓冲区（至少 1）。
 */
int32_t ds_world_entity_at(struct DSWorld *world, size_t index, struct DSEntityState *out);

/**
 * 返回事件流里可用的最大事件数（无输出缓冲时的查询）
 *
 * # Safety
 * `world` 有效。
 */
size_t ds_world_event_count(struct DSWorld *world);

/**
 * 轮询最近的事件：把最多 `max_events` 条事件写入 `out`，返回写入条数。
 *
 * 顺序为**新的在前**（与 HUD 一致）。不消费事件流（多次调用得到同一批）。
 *
 * # Safety
 * `world`、`out` 有效；`out` 需指向至少 `max_events` 个 [`DSEvent`]。
 */
size_t ds_world_poll_events(struct DSWorld *world,
                            struct DSEvent *out,
                            size_t max_events);

#endif  /* DEEPSPACE_H */
